
[general]
	first_time = true
	mod_mode = 0
	link_mode = 1
	send_the_essential_packets = false
	send_the_packets = false
	send_songs_to_servers = false
	allowed_servers = "your.server.here"
	announce_new_song = 0
	notification_album_art_location = 1

[rendering]
	anchor_point = 0
	position_x_offset = 0.0
	position_y_offset = 0.0
	render_type = 2
	display_mode = 2
	controls = false

[login]
	login_button = "login"
	spotify_login_token = ""
	ytmd_password = ""
	service_port = 8880
	refresh_token = ""

