# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				bat = true
				cow = true
				squid = true
				glow_squid = true
				chicken = true
				zombie = true
				skeleton = true
				creeper = true
				sheep = true
				item = true
				enderman = true
				spider = true
				pig = true
				witch = true
				tnt_minecart = true
				zombie_villager = true
				wolf = true
				experience_orb = true
				chest_minecart = true
				slime = true
				fox = true
				villager = true
				iron_golem = true
				mooshroom = true
				salmon = true
				horse = true
				cave_spider = true
				armor_stand = true
				llama = true
				cat = true
				arrow = true
				zombified_piglin = true
				strider = true
				magma_cube = true
				piglin = true
				area_effect_cloud = true
				fishing_bobber = true
				item_frame = true
				donkey = true
				allay = true
				pillager = true
				drowned = true
				experience_bottle = true
				tropical_fish = true
				axolotl = true
				turtle = true
				bee = true
				dolphin = true
				cod = true
				egg = true
				rabbit = true

			[light_sources.settings.entities.ad_astra]
				tier_3_rocket = true

			[light_sources.settings.entities.hookshot]
				hookshot = true

			[light_sources.settings.entities.betternether]
				hydrogen_jellyfish = true
				skull = true
				firefly = true
				naga = true

			[light_sources.settings.entities.ecologics]
				penguin = true

